### ISSUE TITLE
Alias后门利用的alerts.py里newfile()无法写进文件内容

### ISSUE THREAD

**Issue by Deng-Z** [RuoJi6/HackerPermKeeper#1]
通过靶场进行测试，发现newfile()函数好像不能创建/etc/update-manager/release-update这个文件，导致无法写payload
HackerPermKeeper v2.0
OpenSSH后门太过久远，而且很可能会导致ssh连接报错，所以不建议使用[只测试过乌班图14版本成功]
yes----ssh后2门用户
Yes----alerts后门
............
权限为uid=0(root) gid=0(root) groups=0(root)
![image](https://github.com/RuoJi6/HackerPermKeeper/assets/92916343/198289c2-354e-481b-8597-96feb3811c23)

**Comment by RuoJi6** [comment]
好的，感谢提交，此文件是用来其他用户登录的ls命令的上线的，此后会进行修改只用于当前用户，感谢师傅提供bug
